apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: hrms-frontend
  name: hrms-frontend
spec: 
  type: NodePort
  selector: 
    app: hrms-frontend
  ports:
  - name: tcp
    port: 80
    targetPort: 80
    nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrms-frontend
  template:
    metadata:
      labels:
        app: hrms-frontend
    spec:
      containers:
      - name: hrms
        image: hrms--frontend-microservice:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Never
